name: customer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.0
  easy_localization: ^2.3.3
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter_svg: 0.18.1
  get: ^3.22.2
  http: ^0.12.2
  image_picker: ^0.6.7+21
  intl: ^0.16.1
  numberpicker: ^1.3.0
  upi_india: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-light.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
